name: Chris Purchase
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65869
title: Television and Commercial Director - Chris Purchase
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#005e77'
    - '#fffdfd'
    - '#8e8e8e'
    - '#ebaa14'
  brandStrength: 0.5625
  lightness: 0.023488570703193545
  saturation: 0.05844978685490787
  rhythmicContrast: 1
purpose: []
